# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: B3LkKUpcZVx4bpLXKXpiez%R

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  roots-example-project.com:
    env:
      db_password: example_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "xi*j4w}!`W]CQ631Muy5B&>^/kr1l`<Tv5$[4-uK1Xq^i7R7:|t.=O=dR}x(xYu_"
      secure_auth_key: "+<#]lvyFoi8Y^<.e?KU!w,[%GZ)WSU$2,qyhx}uQOblplZ,:QB6)Rl,i^y)Uz]nz"
      logged_in_key: "5P{H?*yFxod@yWD$0BxgE_j?;:hTO{-&$+-55VT_^H+[@^lmGvl3g$BWyQ3l/GCX"
      nonce_key: "t:Ty$Nz,qnt^)h_KNPu^_)EZAYdL.P@|jPo]z@NA]q+%s]1nk>DduDk!:Zbhv]HE"
      auth_salt: "#P>wj1G&mn`]uOEgujE?9=m>@+9,yLrK?BViP:h]^qYZ[&PogcJbYce(`;R@zI_%"
      secure_auth_salt: ">jny;[kr|SsdGzsT]ywS{X6`%r/!XMf4%Jk3U9@awfhNK%We)};Zbg^HAH0-5Ywz"
      logged_in_salt: "L!XSv5wO>T?/F&{n7I36gNzymQ><u7xCX,#|v74jt9O(T>0Xa_a#CoKt(gtNc{V}"
      nonce_salt: "yE,GqLcM>]yG0xrJn]..KZe-,ktlLETs%fcHzBEH^`wFT!7]$#y5_IlL86Tq,y<1"
